# Generated by Django 4.0 on 2022-05-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
