# Generated by Django 4.0 on 2022-06-16 15:09

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_tag_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_to),
        ),
    ]
