# Generated by Django 4.0 on 2022-06-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
