# Generated by Django 4.0 on 2022-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_description_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='../../mysite/static/noimage.jfif', upload_to='', verbose_name='Avatar'),
        ),
    ]
