# Generated by Django 4.0 on 2022-06-05 16:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/noimage.jfif', upload_to=users.models.upload_to),
        ),
    ]
