# Generated by Django 4.0 on 2022-06-28 00:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=users.models.OverwriteStorage(), upload_to=users.models.hash_and_upload),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image', 'user')},
        ),
    ]
