# Generated by Django 4.0 on 2022-05-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_post_comment_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postId',
            new_name='post_id',
        ),
    ]
