# Generated by Django 4.0 on 2022-05-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_postid_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
